# base docker image
FROM ubuntu:24.04

# below is a small set of INSTRUCTIONs for customizing the image as an example


# declare expose port
#EXPOSE 8000

# set environment variable time zone for php installing
#ENV TZ=Europe/Kyiv

# create a new user
#RUN useradd -m user

# create a working directory and give the user rights to it
#WORKDIR /app
#RUN chown -R user:user /app

# switch to a new user
#USER user

# start 
#ENTRYPOINT ["bin/bash"]