services:
  mysql:
    image: mysql:latest
    container_name: mysql
    secrets:
      - mysql-root-password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      TZ: ${TZ}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      TZ: ${TZ}
    ports:
      - "1600:80"
    networks:
      - mysql-phpmyadmin
    depends_on:
      - mysql

networks:
  mysql-phpmyadmin:
    name: mysql-phpmyadmin
    driver: bridge

secrets:
  mysql-root-password:
    file: ./secrets/mysql_root_password.txt